### ISSUE TITLE
Can't get nucleoatac to run

### ISSUE THREAD

**Issue by Angrydutchman** [GreenleafLab/NucleoATAC#13]
I've been trying to get nucleoatac to run and it keeps giving me errors:

$ nucleoatac run --bed /MAF9_ATAC_1st/50920/ChIP_MACS2_peaks/H3K4me1_MACS2_peaks.broadPeak --bam /MAF9_ATAC_1st/50920/nucleoatac/MA9_50K_ATAC.bwt.sort.ppmau.readsorted.bam.crdsrt.bam --fasta /mm9.fai --out /ATAC-seq/MAF9_ATAC_1st/50920/nucleoatac/50KMAF9
Command run:  /usr/bin/nucleoatac run --bed /data/adendekk/ATAC-seq/MAF9_ATAC_1st/50920/ChIP_MACS2_peaks/H3K4me1_MACS2_peaks.broadPeak --bam /data/adendekk/ATAC-seq/MAF9_ATAC_1st/50920/nucleoatac/MA9_50K_ATAC.bwt.sort.ppmau.readsorted.bam.crdsrt.bam --fasta /data/adendekk/indexes/mm9.fai --out /data/adendekk/ATAC-seq/MAF9_ATAC_1st/50920/nucleoatac/50KMAF9
nucleoatac version 0.2.1
start run at: 2015-09-23 17:10
/usr/lib64/python2.7/site-packages/matplotlib/**init**.py:1005: UserWarning:  This call to matplotlib.use() has no effect
because the the backend has already been chosen;
matplotlib.use() must be called _before_ pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
---------Step1: Computing Occupancy and Nucleosomal Insert Distribution---------
Traceback (most recent call last):
  File "/usr/bin/nucleoatac", line 291, in <module>
    main()
  File "/usr/bin/nucleoatac", line 75, in main
    run_occ(occ_args)
  File "/usr/lib/python2.7/site-packages/nucleoatac/run_occ.py", line 92, in run_occ
    fragment_dist.getFragmentSizes(args.bam, chunks)
  File "/usr/lib/python2.7/site-packages/nucleoatac/Occupancy.py", line 27, in getFragmentSizes
    self.fragmentsizes.calculateSizes(bamfile, chunks = chunklist)
  File "/usr/lib/python2.7/site-packages/pyatac/fragmentsizes.py", line 26, in calculateSizes
    sizes = getFragmentSizesFromChunkList(chunks, bamfile, self.lower, self.upper, atac = self.atac)
  File "pyatac/fragments.pyx", line 130, in pyatac.fragments.getFragmentSizesFromChunkList (/home/adendekk/.pyxbld/temp.linux-x86_64-2.7/pyrex/pyatac/fragments.c:4724)
    for read in bamHandle.fetch(chunk.chrom, max(0, chunk.start - upper), chunk.end + upper):
  File "pysam/calignmentfile.pyx", line 740, in pysam.calignmentfile.AlignmentFile.fetch (pysam/calignmentfile.c:10083)
ValueError: fetch called on bamfile without index

Not sure what the problem is.  I've tried to install it globally and run it and also in virtual environment with updated dependencies.  I've used BAM sorted by coordinate and also by name.  I've tried BAM files and also indexed BAM files.  Please help.

**Comment by AliciaSchep** [comment]
Bam should be sorted by coordinate and needs to be indexed-- seems like in the error output that there is no index (as it says: "ValueError: fetch called on bamfile without index").  The bam index file must have the same name as the bam file plus the ending ".bai" and must be located in the same folder (these are requirements from pysam module).  What error occurs if you use a bam file that is indexed?

As for the warning about the matplotlib, I am not sure why that is occurring  or whether it will have an effect

**Comment by Angrydutchman** [comment]
Thanks.  I had the bam file indexed but had moved the the bam file to another directory to run the process.  NucleoATAC couldn't access the index.  Once you mentioned the index I realized the issue.
