### ISSUE TITLE
--not_atac  definition clarification?

### ISSUE THREAD

**Issue by msg63** [GreenleafLab/NucleoATAC#14]
Hi Alicia,
Several pyatac subcommands use the option " --not_atac" defined as: 
--not_atac      Don't use atac offsets
Is this referring to +4bp and -5pb offset of read start sites aligning to + and - strand?
In other words, by default, does pyatac adjusts the read start sites by +4bp/-5bp?

Thanks!

Mohsen

**Comment by AliciaSchep** [comment]
Yes, that is referring to the 4bp offset -- reads will be automatically adjusted unless the "--not_atac" flag is used
