### ISSUE TITLE
nucleoatac nfr problem

### ISSUE THREAD

**Issue by will-NYGC** [GreenleafLab/NucleoATAC#15]
I'm having a little problem with what looks like the "nucleoatac nfr" module. Everything else seems to run fine. I'm trying to use "nucleoatac run" so I'm confused as to why it tries to run "nfr". I thought "run" was a wrapper for "occ" "vprocess" and "nuc"? Is this an issue with my input BAM?

thanks!

Traceback:
Traceback (most recent call last):
  File "/nfs/sw/nucleoatac/nucleoatac-0.2.1/nucleoatac/run_nfr.py", line 26, in _nfrHelper
    nfr.process(params)
  File "/nfs/sw/nucleoatac/nucleoatac-0.2.1/nucleoatac/NFRCalling.py", line 103, in process
    self.getIns()
  File "/nfs/sw/nucleoatac/nucleoatac-0.2.1/nucleoatac/NFRCalling.py", line 74, in getIns
    self.ins.calculateInsertions(self.params.bam)
  File "/nfs/sw/nucleoatac/nucleoatac-0.2.1/pyatac/tracks.py", line 168, in calculateInsertions
    self.vals = getInsertions(bamfile, self.chrom, self.start, self.end, lower, upper, atac)
  File "pyatac/fragments.pyx", line 56, in pyatac.fragments.getInsertions (/nethome/wliao/.pyxbld/temp.linux-x86_64-2.7/pyrex/pyatac/fragments.c:2911)
    ilen = abs(read.template_length) - 8
OverflowError: can't convert negative value to unsigned int
Traceback (most recent call last):
  File "/nfs/sw/nucleoatac/nucleoatac-0.2.1/bin/nucleoatac", line 291, in <module>
    main()
  File "/nfs/sw/nucleoatac/nucleoatac-0.2.1/bin/nucleoatac", line 83, in main
    run_nfr(nfr_args)
  File "/nfs/sw/nucleoatac/nucleoatac-0.2.1/nucleoatac/run_nfr.py", line 98, in run_nfr
    tmp = pool1.map(_nfrHelper, zip(j,itertools.repeat(params)))
  File "/nfs/sw/python/python-2.7.8/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/nfs/sw/python/python-2.7.8/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
OverflowError: can't convert negative value to unsigned int

**Comment by AliciaSchep** [comment]
this occurs when a bam file has a fragment that is less than 8 bp long, which should be an impossibility with ATAC-seq but can occur if aligner clips reads.  I plan to fix the fact that this causes an error (i.e will change to ignore fragments short). In meantime, if you filter out reads less than 8 bp long this error should not occur

**Comment by will-NYGC** [comment]
hi alicia,

do you mean template length less than 8bp? meaning the TLEN value in SAM format? I’ve filtered by TLEN with both <8 and just to check <9 and still get this error.

On Oct 1, 2015, at 9:08 PM, Alicia Schep <notifications@github.com<mailto:notifications@github.com>> wrote:

this occurs when a bam file has a fragment that is less than 8 bp long, which should be an impossibility with ATAC-seq but can occur if aligner clips reads. I plan to fix the fact that this causes an error (i.e will change to ignore fragments short). In meantime, if you filter out reads less than 8 bp long this error should not occur

—
Reply to this email directly or view it on GitHubhttps://github.com/GreenleafLab/NucleoATAC/issues/15#issuecomment-144892258.

This electronic message is intended for the use of the named recipient only, and may contain information that is confidential, privileged or protected from disclosure under applicable law. If you are not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any reading, disclosure, dissemination, distribution, copying or use of the contents of this message including any of its attachments is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and destroy all copies of this message. Please note, the recipient should check this email and any attachments for the presence of viruses. The organization accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by AliciaSchep** [comment]
Yes I mean TLEN value in SAM format.  You get the exact same error when those fragments are filtered out?  I will look into what else could cause that error.

**Comment by will-NYGC** [comment]
Hi Alicia,

actually, gave it another try, filtering TLEN <8bp and it seems to be ok right now. If I see the error again, will update but i think that did in fact fix the problem.

On Oct 9, 2015, at 6:24 PM, Alicia Schep <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes I mean TLEN value in SAM format. You get the exact same error when those fragments are filtered out? I will look into what else could cause that error.

—
Reply to this email directly or view it on GitHubhttps://github.com/GreenleafLab/NucleoATAC/issues/15#issuecomment-146999541.

This electronic message is intended for the use of the named recipient only, and may contain information that is confidential, privileged or protected from disclosure under applicable law. If you are not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any reading, disclosure, dissemination, distribution, copying or use of the contents of this message including any of its attachments is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and destroy all copies of this message. Please note, the recipient should check this email and any attachments for the presence of viruses. The organization accepts no liability for any damage caused by any virus transmitted by this email.
