### ISSUE TITLE
Question about vprocess for mammalian data

### ISSUE THREAD

**Issue by Angrydutchman** [GreenleafLab/NucleoATAC#17]
The help page for the vprocess subcommand mentions an optional argument for VMat files and that the default is the vplot file for S ceriv.  How does this impact running this function for mouse or human data and how can I generate or obtain a VMat files for mouse or human in order to run the vprocess command?  I apologize if this seems obtuse, I'm a newcomer to this type of analysis.

**Comment by AliciaSchep** [comment]
Hi, Yes the default can be used for mammalian data as well. The vprocess function is adjusting the vplot based on the estimated nucleosomal fragment size distribution for the sample that is being used.  The major assumption that is being made is that the constraints on Tn5 insertion at boundary of nucleosome are similar between species.  The similarity in positions of local maxima for the fragment size distribution between species suggests that this is the case.
