### ISSUE TITLE
test data set

### ISSUE THREAD

**Issue by EricDeveaud** [GreenleafLab/NucleoATAC#19]
Hi, 

while trying install nucleoatac on our central HPC cluster I wasn't able to run a **functional test**  (ie, post install before delivering it to our users) of the freshly installed nucleoatac. because of the lack of the necessary fastafile as mentioned on the doc.
I was trying to run the following command: 

```
nucleoatac run --bed <bedfile> --bam <bamfile> --fasta <fastafile> --out <output_basename>
```

with the example bead bam  files provided, but I was missing the fastafile.

can you provide one or the reference to the one used  

regards

Eric

**Comment by AliciaSchep** [comment]
The one that would be used is sacCer3 from UCSC genome browser.  I should add it to the example folder.

**Comment by EricDeveaud** [comment]
thanks 
Eric
