### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by OscarBrock** [GreenleafLab/NucleoATAC#23]
Hello, 

I'm getting the following runtime error when running nucleoATAC. Any guess as to what I might be doing wrong? 
# 

Command run:  /gne/home/bainerr/miniconda3/envs/ATACseq/bin/nucleoatac run --bed /gne/home/bainerr/Workspace/ATACseq/Jackson/ATACpilot/lungline_10.macsmerge.bed --bam /gne/home/bainerr/Workspace/ATACseq/Jackson/ATACpilot/filtered.lungline_10.bam --fasta /gne/research/apps/ngs_pipeline/4.0.2/x86_64-linux-2.6-rhel6/genome_files/GATK/GRCm38.fa --out filtered.lungline_10
nucleoatac version 0.3.0
start run at: 2015-10-23 09:17
---------Step1: Computing Occupancy and Nucleosomal Insert Distribution---------
Traceback (most recent call last):
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/bin/nucleoatac", line 291, in <module>
    main()
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/bin/nucleoatac", line 75, in main
    run_occ(occ_args)
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/site-packages/nucleoatac/run_occ.py", line 96, in run_occ
    fragment_dist.modelNFR()
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/site-packages/nucleoatac/Occupancy.py", line 40, in modelNFR
    p0=p0)
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/site-packages/scipy/optimize/minpack.py", line 586, in curve_fit
    raise RuntimeError(msg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 800.

**Comment by AliciaSchep** [comment]
What does the fragment size distribution for that sample look like within those regions? (You can get the fragment size distribution within your peak regions using the command 'pyatac sizes --bam name-of-bam-file.bam --bed name-of-bed-file.bed' ). If you could potentially attach both the figure and the text file output of the sizes command that would be very helpful for diagnosing the problem.

version 0.3.0 has a new function to fit the NFR distribution that ideally should be more robust than previous versions and has worked well on a variety of samples I tested it on, but my collection of test cases likely doesn't cover all the different possibilities for the fragment size distribution

**Comment by OscarBrock** [comment]
Hi Alicia,

Sorry to be slow. Here is what I get.

On Fri, Oct 23, 2015 at 6:40 PM, Alicia Schep notifications@github.com
wrote:

> What does the fragment size distribution for that sample look like within
> those regions? (You can get the fragment size distribution within your peak
> regions using the command 'pyatac sizes --bam name-of-bam-file.bam --bed
> name-of-bed-file.bed' ).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GreenleafLab/NucleoATAC/issues/23#issuecomment-150736179
> .

#lower
0
#upper
500
#sizes
7.54592695276e-06   5.28214886693e-05   3.10714639231e-06   4.03929031001e-05   1.46479758495e-05   1.77551222418e-06   4.03929031001e-05   4.43878056045e-07   4.21684153243e-05   4.43878056045e-07   2.53010491946e-05   7.54592695276e-06   1.81990002978e-05   3.55102444836e-05   3.9949025044e-06    2.30816589143e-05   6.21429278463e-06   4.30561714364e-05   0.000394163713768   0.000900184697659   0.00256073250532    0.00404594848085    0.00569273606878    0.00369617257269    0.00231304855005    0.0022065178166 0.00249858957748    0.00275648272804    0.00221184435327    0.00503357715555    0.00884648965698    0.011167084134  0.0209648044651 0.0217633410879 0.0145054909935 0.0122958660305 0.0101235268242 0.0098247968925 0.0103374760472 0.0106117926859 0.00893082648762    0.0114538293582 0.0157656607946 0.0188643735039 0.0167057945173 0.0147238789971 0.0112376607449 0.00839950445454    0.00904357151386    0.00866006087344    0.00764979441788    0.0086463006537 0.00883228555918    0.0113601710884 0.0118373399986 0.0109500277646 0.0090977246367 0.00918827576013    0.00740965638956    0.00710471216506    0.00618011417431    0.00650636454551    0.00571359833741    0.00636121642118    0.00685658433173    0.0065831554492 0.00651524210663    0.00533763362394    0.0060580477089 0.00476858195609    0.00535627650229    0.00461544402676    0.00428297936278    0.00407835157894    0.00428386711889    0.00460301544119    0.00507130679031    0.00514188340122    0.00396116777214    0.00448050509772    0.00396383104048    0.00417689250738    0.00410587201842    0.00384664723369    0.00424081094745    0.00381380025754    0.003429401861  0.00379382574502    0.00330156498086    0.00330866702976    0.00315464134431    0.00314088112457    0.00310847802648    0.00252033960222    0.00290784514515    0.00272363575189    0.00280974809476    0.00296554929244    0.00277468172834    0.00303612590335    0.00253765084641    0.00226777298833    0.00232592101368    0.00210797688816    0.00237297208762    0.00206891561923    0.00209821157092    0.00233968123341    0.00250214060193    0.00248127833329    0.00252788552918    0.00217589023073    0.0019823593983 0.00175864485805    0.00209466054648    0.00192066034851    0.00233568633091    0.00187449703068    0.00231793120867    0.00179903776115    0.00208001257063    0.00194862466604    0.00189225215292    0.00184342556675    0.00159707324565    0.00189669093348    0.00162193041679    0.00226111481749    0.00188293071374    0.00215813510849    0.00247595179662    0.00224247193914    0.00186561946956    0.00157621097702    0.00193619608047    0.00143283836491    0.00187671642096    0.00189669093348    0.00167563966157    0.0017954867367 0.00247994669912    0.0020489411067 0.00230594650115    0.00237652311206    0.0021186299615 0.0018944715432 0.00163791002681    0.00185319088399    0.00183499188369    0.0019823593983 0.00235255369704    0.00225756379304    0.0021297269129 0.00223359437802    0.00182167554201    0.00188293071374    0.00167563966157    0.00263308462846    0.00187893581124    0.0022287117194 0.00221939028022    0.00213460957152    0.00261932440872    0.00211552281511    0.00227132401278    0.00217100757212    0.00233790572119    0.00229041076919    0.00267614079989    0.0023751914779 0.00241824764933    0.00234145674564    0.00207468603395    0.00268856938546    0.00234678328231    0.0023640945265 0.00266548772655    0.0023751914779 0.00287366653483    0.0026397427993 0.0023458955262 0.00224602296359    0.00215103305959    0.00268990101963    0.00207512991201    0.00242579357629    0.00265749792154    0.00307651880645    0.0024488752352 0.00272629902023    0.00241380886877    0.00260778357926    0.00249370691886    0.00271608982494    0.00249015589441    0.00259269172536    0.00302236568361    0.00280619707032    0.00290518187681    0.00273473270329    0.0025367630903 0.00212395649817    0.00262287543317    0.00237030881928    0.0025993498962 0.00238717618541    0.00253409982196    0.00293447782851    0.00224380357331    0.00209155340008    0.0024306762349 0.00203606864308    0.0020378441553 0.00213105854707    0.00192066034851    0.00204849722865    0.0019974512522 0.00223892091469    0.0021186299615 0.00177595610224    0.0016854049788 0.00181546124922    0.00163746614875    0.00132009333868    0.00159396609926    0.00195883386133    0.00169161927159    0.00202941047224    0.0015460272692 0.0017479917847 0.00137513421763    0.00158198139174    0.0014208536574 0.00155623646449    0.00115985336045    0.00123264936164    0.00141819038906    0.00147278738996    0.00124951672777    0.00123087384941    0.00117894011686    0.00104045016337    0.00111901657929    0.00110214921316    0.00136314951011    0.000935694942143   0.00106885835896    0.00100138889444    0.00110126145705    0.000879766307081   0.001156302336  0.000959220479113   0.000901072453771   0.00107107774924    0.000905067356276   0.00103867465115    0.000998725626101   0.000809633574226   0.000657383401003   0.000874439770409   0.000796317232545   0.000794985598376   0.00100715930917    0.000863342819007   0.00103157260225    0.000648061961826   0.000666704840179   0.000723521231353   0.000832271355084   0.000919715332125   0.000770128427238   0.000789659061704   0.0010502154806 0.000668480352404   0.000549521033384   0.00077101618335    0.000816735623123   0.000812740720618   0.000614327229566   0.000542862862543   0.000685347718533   0.000788771305592   0.000678689547693   0.000610776205118   0.000762582500285   0.000564169009233   0.000905067356276   0.000623204790687   0.000706209987167   0.000563725131177   0.000410587201842   0.000722633475241   0.000724408987465   0.000636965010424   0.000453643373278   0.000667592596292   0.000750153914716   0.000501582203331   0.000659158913227   0.00055662308228    0.000670699742684   0.00062853132736    0.000710204889672   0.000641847669041   0.000827388696468   0.000697776304103   0.000664485449899   0.000620985400407   0.000557066960336   0.000666704840179   0.000605005790389   0.000631638473752   0.000554847570056   0.000722189597185   0.000697776304103   0.000721745719129   0.000679577303805   0.000482939324977   0.000614327229566   0.000533541423366   0.000510903642508   0.000499806691107   0.000525107740301   0.000682684450197   0.000612107839286   0.000410143323786   0.000545082252823   0.000626311937079   0.000498475056938   0.000669368108516   0.000553515935888   0.000624536424855   0.000759475353893   0.000680908937973   0.000638740522649   0.000421240275187   0.000700439572439   0.000506908740003   0.00045231173911    0.000560617984785   0.000692005889374   0.000731511036362   0.000715087548288   0.00073284267053    0.000551740423664   0.000627643571248   0.000640072156817   0.000539755716151   0.000805638671722   0.00064761808377    0.000728847768026   0.000700883450495   0.000758143719725   0.000560174106729   0.000533985301422   0.000737281451091   0.000896633673211   0.000637408888481   0.000633857864032   0.000759919231949   0.000624536424855   0.000703546718831   0.000733730426642   0.000605005790389   0.000706209987167   0.000711092645784   0.000637408888481   0.000676470157412   0.000677357913525   0.000974756211075   0.000716863060513   0.000743051865819   0.000723077353297   0.000684903840477   0.000454975007446   0.000670699742684   0.000702658962719   0.000783888646975   0.000583699643699   0.000562837375065   0.000573046570354   0.000723521231353   0.000691562011318   0.000586362912035   0.00069466915771    0.000871776502072   0.000529990398918   0.000521112837797   0.000599235375661   0.000520225081685   0.00054996491144    0.000553959813944   0.000661378303507   0.000566388399513   0.000627643571248   0.000499362813051   0.000610332327062   0.000585475155923   0.000599235375661   0.000426122933803   0.000490929129986   0.000643179303209   0.000521112837797   0.000371082054854   0.000441214787709   0.000405260665169   0.000622317034575   0.000520225081685   0.000459413788007   0.000506908740003   0.000407923933505   0.000535760813646   0.000449648470774   0.000486490349425   0.000444321934101   0.000342673859267   0.0004736178858 0.000464296446623   0.000445653568269   0.000511347520564   0.000393275957656   0.000535760813646   0.000388837177095   0.000462964812455   0.000498918934995   0.000454087251334   0.000619653766239   0.000451867861054   0.000580148619251   0.000469179105239   0.000408367811561   0.000351551420388   0.000400378006553   0.000355990200948   0.000405704543225   0.000349332030107   0.000401709640721   0.000305831980615   0.000365311640125   0.000367087152349   0.000305388102559   0.000427010689915   0.000191311442155   0.000460745422175   0.000351995298444   0.000317372810072   0.000284081955869   0.000309383005063   0.000304944224503   0.000366199396237   0.000262331931123   0.000249459467497   0.00027609215086    0.000236143125816   0.000206847174117   0.000197081856884   0.00015491344156    0.000286745224205   0.000379071859862   0.000338235078706   0.000302724834223   0.000233923735536   0.000213505344958   0.000250791101665   0.000279643175308   0.00029961768783    0.000272097248356   0.000269433980019   0.000146923636551   0.000192199198267   0.000215724735238   0.000217500247462   0.000268102345851   0.000383954518479   0.000241025784432   0.000367531030405   0.000273428882524   0.000311158517287   0.000259668662786   0.000233923735536   0.000196194100772   0.000274316638636   0.000205071661893   0.000185541027427   0.000324030980913   0.000156688953784   0.00024013802832    0.000173112441858   0.000186428783539   0.000339566712874   0.000218388003574   0.000251234979721   0.000167342027129   0.000288520736429   0.000165122636849   0.000181546124922   0.000183765515203   0.000222382906079   0.00019974512522    0.000223270662191

**Comment by AliciaSchep** [comment]
Thanks for providing the output.  I was able to reproduce the error. 

The issue arose due to a change I made in v0.3.0 for fitting the fragment size distribution (distribution used for fitting was changed from exponential to gamma; one more free parameter).  The change improved the behavior of the fit for some observed distributions, but as initially implemented was problematic in that it didn't take into account the fact that minimum possible fragment size is greater than zero. I have modified that fit function some more in v0.3.1 to take that fact into account; ideally it will be more robust -- I have tested it across my set of atac-seq fragment distributions as well as the one you provided and it works for each distribution.

**Comment by OscarBrock** [comment]
Awesome, thanks for your prompt update.

**Comment by OscarBrock** [comment]
Hi Alicia, 

I'm afraid that now I am getting a gcc error.... any suggestions? 

# 

/tmp/ccCFwqMG.s: Assembler messages:
/tmp/ccCFwqMG.s:130547: Fatal error: can't write /gne/home/bainerr/.pyxbld/temp.linux-x86_64-2.7/gne/home/bainerr/.pyxbld/temp.linux-x86_64-2.7/pyrex/pyatac/fragments.o: No space left on device
/tmp/ccCFwqMG.s:130547: Fatal error: can't close /gne/home/bainerr/.pyxbld/temp.linux-x86_64-2.7/gne/home/bainerr/.pyxbld/temp.linux-x86_64-2.7/pyrex/pyatac/fragments.o: Stale file handle
Command run:  /gne/home/bainerr/miniconda3/envs/ATACseq/bin/nucleoatac run --bed /gne/home/bainerr/Workspace/ATACseq/Jackson/ATACpilot/30bp_alignment_.concordant_uniq.macsmerge.bed --bam /gne/home/bainerr/Workspace/ATACseq/Jackson/ATACpilot/filtered.30bp_alignment_.concordant_uniq.bam --fasta /gne/research/apps/ngs_pipeline/4.0.2/x86_64-linux-2.6-rhel6/genome_files/GATK/GRCm38.fa --out filtered.30bp_alignment_.concordant_uniq
nucleoatac version 0.3.1
start run at: 2015-10-28 13:03
Traceback (most recent call last):
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/bin/nucleoatac", line 291, in <module>
    main()
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/bin/nucleoatac", line 69, in main
    from nucleoatac.run_occ import run_occ
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/site-packages/nucleoatac/run_occ.py", line 19, in <module>
    from nucleoatac.Occupancy import FragmentMixDistribution, OccupancyParameters, OccChunk
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/site-packages/nucleoatac/Occupancy.py", line 12, in <module>
    from pyatac.fragmentsizes import FragmentSizes
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/site-packages/pyatac/fragmentsizes.py", line 10, in <module>
    from pyatac.fragments import getAllFragmentSizes, getFragmentSizesFromChunkList
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/site-packages/pyximport/pyximport.py", line 435, in load_module
    language_level=self.language_level)
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/site-packages/pyximport/pyximport.py", line 227, in load_module
    exec("raise exc, None, tb", {'exc': exc, 'tb': tb})
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/site-packages/pyximport/pyximport.py", line 209, in load_module
    inplace=build_inplace, language_level=language_level)
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/site-packages/pyximport/pyximport.py", line 186, in build_module
    reload_support=pyxargs.reload_support)
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/site-packages/pyximport/pyxbuild.py", line 100, in pyx_to_dll
    dist.run_commands()
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/site-packages/Cython/Distutils/build_ext.py", line 164, in run
    _build_ext.build_ext.run(self)
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/distutils/command/build_ext.py", line 337, in run
    self.build_extensions()
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/site-packages/Cython/Distutils/build_ext.py", line 172, in build_extensions
    self.build_extension(ext)
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/distutils/command/build_ext.py", line 496, in build_extension
    depends=ext.depends)
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/distutils/unixccompiler.py", line 122, in _compile
    raise CompileError, msg
ImportError: Building module pyatac.fragments failed: ["CompileError: command 'gcc' failed with exit status 1\n"]

**Comment by AliciaSchep** [comment]
Haven't seen that particular issue before and am not too sure  what hose error messages mean... At the top thought it says "Fatal error: can't write /gne/home/bainerr/.pyxbld/temp.linux-x86_64-2.7/gne/home/bainerr/.pyxbld/temp.linux-x86_64-2.7/pyrex/pyatac/fragments.o: No space left on device"  -- is there very limited space in the folder that the file is being built in?

**Comment by OscarBrock** [comment]
There shouldn't be (it's running on a cluster), but I will check on my end
to see if there is something I can do. Do you have a guess as to how big
that file should be?

-R

**Comment by AliciaSchep** [comment]
not very big, so its a pretty strange message

**Comment by wgb** [comment]
This is likely an issue with the OS running out of space on the tmpfs at compile time since the trace starts from `/tmp/[arbitrary]/`. Usually the default space allocated for the tmpfs is set to half the size of the RAM, but that size can be set explicitly in `/etc/fstab` to any size so long as it doesn't exceed total available RAM + swap space. See [this](https://www.kernel.org/doc/Documentation/filesystems/tmpfs.txt) and [this](https://wiki.archlinux.org/index.php/Tmpfs) for references to increase tmpfs allocation.

**Comment by OscarBrock** [comment]
Thanks. As a workaround I cleared out a lot of extra space on the drive in
question and it seems to be executing stably now. Marking as resolved.
