### ISSUE TITLE
Regarding PWM Mouse Genome

### ISSUE THREAD

**Issue by ShaluJhanwar** [GreenleafLab/NucleoATAC#24]
Hi,
I want to use NucleoATAC to identify nucleosomes from ATAC-seq data in Mouse. I am wondering could you please let me know if you have PWM​ files for Mouse or any source from where I can get/generate it in the format NucleoATAC uses.
Thanks!

**Comment by AliciaSchep** [comment]
Hi, PWM file should be pretty similar for any species as it is simply reflecting sequence preferences of nextera Tn5 on naked dna.  The ones included are from Human and Yeast genomic dna samples and are both very similar. If not using nextera Tn5 (i.e. using some other transposase) then  a new pwm should be created based on a genomic dna sample.
