### ISSUE TITLE
Mapped reads on Nucleosomes

### ISSUE THREAD

**Issue by ShaluJhanwar** [GreenleafLab/NucleoATAC#26]
Hi,
I want to plot reads mapped per nucloesome position. 
i) Could you please let me know which file from NucleoATAC can provide me reads mapped per nucleosome around ATAC?
ii) NucleoATAC provides only dyad positions. How many bp flanking can provide an approximation of the actual nucleosome peak ? I am considering 100bp flanking nucleosome dyad position.
Thanks!
Shalu

**Comment by AliciaSchep** [comment]
i) Descriptions of the output files is in the [documentation](http://nucleoatac.readthedocs.org/en/latest/nucleoatac/#nuc). Columns 11 or 12 of *.nucpos.bed.gz might be what you're looking for
ii)  Generally 147 bp of DNA is thought to wrap around nucleosome.  How much linker between nucleosomes will vary between species and possibly even cell types... but your data should be able to inform this
