### ISSUE TITLE
Plots of paper Figure 1c

### ISSUE THREAD

**Issue by antgomo** [GreenleafLab/NucleoATAC#31]
I want to reproduce the Figure 1 c of the Genome Research paper, basically the ATAC insertions for several different samples. So, must I use the signal or occ files? 
The point is , as far as I see, that I have in this bed files the position of the nucleosome dyad, 2bp, so (maybe is a naïve quiestion, sorry) how can I plot the same figure as in Fig 1c with this kind of files?

Thanks in advance

**Comment by AliciaSchep** [comment]
Figure 1c is the ATAC-seq insertions around nucleosome calls by chemical mapping from Brogaard et al.  NucleoATAC (`nucleoatac run`) should create a ".ins.bedgraph.gz" file.  You can also just create that bedgraph file by running `pyatac ins`.  

For getting the chemical mapping calls, you'd have to refer to Brogaard et al paper.
