### ISSUE TITLE
Combining replicates 

### ISSUE THREAD

**Issue by PFRoux** [GreenleafLab/NucleoATAC#35]
Dear Alicia,

I am wondering whether we've already been thinking about a smart way to combine the results reported by NucleoATAC for several biological replicates in a given condition ?

Thanks a lot !

Pierre-François

**Comment by AliciaSchep** [comment]
Not really!  In general to combine results I've run NucleoATAC on pooled bam files from several replicates to take advantage of greater read depth.  Of course running it separately on replicates can potentially be useful for validating differences between conditions.

**Comment by PFRoux** [comment]
Thanks Alicia. I'll probably try to consider replicates independently to gain in accuracy.

**Comment by ATpoint** [comment]
Hey,
did you normalize the files to each other in any fashion before merging them?

**Comment by AliciaSchep** [comment]
No, simple merge.
