### ISSUE TITLE
Input bam and bed

### ISSUE THREAD

**Issue by josegarciamanteiga** [GreenleafLab/NucleoATAC#36]
Hi,
First of all thanks for the great tool!
I have a question on the input files. Since I have been using the protocols in the original Buenrostro et al. with DANPOS I have a doubt:
Do I have to shift (+4 -5bp) the input bam? Do I have to do it on the bed? (or peak call on a preshifted bam?)
Thanks in advance
Jose

**Comment by AliciaSchep** [comment]
Nope!  You should not shift the input bams, as that will be done internally by the program

**Comment by josegarciamanteiga** [comment]
Great!
Thanks for the info, since it was not clear in the nucleoatac info whether this should be done before or not. I understand, though, that the bed file with peaks called should be produced on the shifted bam. Is that right?
Thanks again
J

**Comment by AliciaSchep** [comment]
It likely doesn't make a big difference for peak calling.
