### ISSUE TITLE
nucleoatac .nucpos.bed problem

### ISSUE THREAD

**Issue by danimschwartz** [GreenleafLab/NucleoATAC#38]
Hi Alicia, 

I used nucleoatac on my ATAC-seq samples in mouse helper T cells. The software runs with no errors, and I get all of the appropriate output files. However, the nucpos.bed.gz files and nucpos.redundant.bed.gz files are empty even though the remaining files look OK, including the signal.bedgraphs with cross-correlation signal, which clearly show signal at multiple loci. I checked the fragment size, and while the peak at 150-200bp is low relative to the smaller fragments, it's there. I am attaching representative images of the fragment size distribution/V-plot and would appreciate any help/advice. 

Thanks,
Daniella

[nucleoatac_output_2.nuc_dist.pdf](https://github.com/GreenleafLab/NucleoATAC/files/252256/nucleoatac_output_2.nuc_dist.pdf)
[nucleoatac_output_2.occ_fit.pdf](https://github.com/GreenleafLab/NucleoATAC/files/252257/nucleoatac_output_2.occ_fit.pdf)
[nucleoatac_output_2.VMat.pdf](https://github.com/GreenleafLab/NucleoATAC/files/252258/nucleoatac_output_2.VMat.pdf)

**Comment by AliciaSchep** [comment]
Plots look reasonable, not sure what might be the issue might be.  Did you figure it out?  What is the read depth, how many regions are you looking at?

**Comment by danimschwartz** [comment]
Hey,
I think the issue might be that I didn’t realize I was supposed to use broad peaks — I muse have missed that part of the instructions when reading through the usage on your website. I used narrow peak calling to generate my bedfiles (using MACS 1.4), and I didn’t merge or remove the duplicates. So I ended up with ~40,000 peaks ranging in length from 83-2000bp, but mostly in the <500bp range).
Re: the read depth – I had 15-20 million PE reads per sample.
I am going to try it again with broad peaks and keep my fingers crossed that this will fix the issue.
Thanks for the email,
Dani

**Comment by danimschwartz** [comment]
Redid the peak calling for broad peaks, used bedtools slop, and merged to ensure no duplicates.
The program ran no problem, and I still get occpeaks bedgraphs/bedfiles, nfrpos bedfiles, and signal/signal_smooth bedgraphs.
Any ideas of how to fix the issue?
Thanks,
Daniella

**Comment by AliciaSchep** [comment]
Sorry I don't know what this could be!  Perhaps can you include a screenshot of the nucleoatac_signal on a genome browser?

**Comment by igordot** [comment]
I think I ran into the same problem. Here is my screenshot of nucleoatac_signal and the smooth version. I got over 50,000 occ peaks with that sample, but none with nucpos.

![image](https://cloud.githubusercontent.com/assets/6363505/18817972/71f9c97e-833b-11e6-9b65-2d120ffa8ef8.png)
