### ISSUE TITLE
Plots for Figure 4 E

### ISSUE THREAD

**Issue by khayer** [GreenleafLab/NucleoATAC#40]
Could you please comment on which output file you used to create figure 4e? Similarly can NucleoATAC be used to create Figure 3 C from [Buenrostro et al. 2013](http://www.nature.com/nmeth/journal/v10/n12/full/nmeth.2688.html)? 

Thanks in advance

**Comment by AliciaSchep** [comment]
The output file was the nucleoatac_signal.bedgraph.gz output.  The supplement shows heatmaps at the TSS for both the nucleoatac_signal and the occupancy (Supplementary Figure 16).  

Sure it could be used to create something like Figure 3C.  You could potentially make a coverage track (using pyatac cov) and then multiply by the occupancy track (to get a level of nucleosome coverage) and by (1 - occupancy track) to get a level of nfr coverage.
