### ISSUE TITLE
Best way to normalize outputs for comparisons between conditions ?

### ISSUE THREAD

**Issue by PFRoux** [GreenleafLab/NucleoATAC#42]
Dear Alicia,

Do you have any advice for normalizing the outputs (i.e. occ signals or nucleoatac_signal) before comparing results obtained for different conditions / samples ?
Is downsampling the bam files before running the NucleoATAC workflow the way to go ? 

Thanks a lot !

Best,

Pef

**Comment by AliciaSchep** [comment]
For occ_signal the signal shouldn't be sensitive to sequencing depth except when looking at regions with low coverage, however different signal to noise ratios can lead to systematic differences (more noise tends to just deflate occupancy everywhere).  For determining whether that is an issue I tend to look at whether there are global differences in the score and/or differences in internal "control regions" (regions where I don't expect changes).  

the nucleoatac_signal will be very sensitive to sequencing depth... for comparing that downsampling might sense.  Even with downsampling though I would advise caution in that if there is an increase in the accessibility of linkers that will lead to more signal but shouldn't be equated with greater nucleosome occupancy.
