### ISSUE TITLE
Optimizing run time

### ISSUE THREAD

**Issue by will-NYGC** [GreenleafLab/NucleoATAC#43]
Hi, I have ATAC-seq libraries with between 200-300M mapped reads and NucleoATAC is taking in the order of 5-10 days to run. I'm using 4 cores, as well, and and am hesitant to increase this b/c of increased memory demands. Do you have any suggestions as to how to speed up run times?

**Comment by AliciaSchep** [comment]
I would look at what fraction of the genome you are running it, if your peak calling is quite liberal, it might make sense to run it on peaks with higher coverage only (what is read count for weakest peak?).  Don't really have any tips beyond that and increasing cores unfortunately.

**Comment by will-NYGC** [comment]
thanks for suggestion. Do you have any guidance as to the level of minimum coverage needed to get useful results from NucleoATAC?

**Comment by AliciaSchep** [comment]
addressed in #50
