### ISSUE TITLE
Profile plot using NucleoATAC around peak centers

### ISSUE THREAD

**Issue by sudhirthakurela** [GreenleafLab/NucleoATAC#45]
Hi Alicia, 

I am looking to make something like shown in Fig 3a/b of this paper:
https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-0897-0

I have a similar experiment with pre and post induction of a factor and regions that remain close or regions that open up (based on ATAC signal) after TF induction. I would like to show nucleosome positioning in these 2 sets of regions pre and post induction. 

I ran NuceloATAC and it worked perfectly and can see in V-plot that there is very visible change in nucelosome positions. However, I would like to show it for larger regions (not +/- 60) and also as a profile plot and heatmap around the centre of peaks. 

May I know which files to use and if anything else I would need to do to get smooth signal?

Thanks and regards,
Sudhir

**Comment by AliciaSchep** [comment]
For a profile plot you can use pyatac signal command, you can see options if you do `pyatac signal --help`  There should be options to use strand information of input regions and to set how many basepairs around site to consider.
