### ISSUE TITLE
extending regions

### ISSUE THREAD

**Issue by igordot** [GreenleafLab/NucleoATAC#46]
The documentation mentions "It is potentially advisable to extend these regions a bit (e.g. using bedtools slop)". How much is a bit? Is there a downside in extending them too much other than increasing runtime?

**Comment by AliciaSchep** [comment]
By a bit I meant 100-200 bp.  Main downside with extending by a lot is increased runtime-- in regions with fewer reads, there is less power to detect nucleosomes so it is likely a waste of time. It will also dilute quality of nucleosome positioning calls. Already when looking within peaks you want to keep in mind that absence of nucleosome call does not mean absence of nucleosome (could just be insufficient reads).
