### ISSUE TITLE
PWM descriptor file

### ISSUE THREAD

**Issue by igordot** [GreenleafLab/NucleoATAC#47]
Default PWM descriptor file is Human.PWM.txt included in package. How can I generate it for other species?

You previously mentioned (https://github.com/GreenleafLab/NucleoATAC/issues/24) that even human and yeast are very similar, so it's probably fine to use human file with mouse data. Is it worth generating the files for other species like fly or worm?

**Comment by AliciaSchep** [comment]
Very late response, but for reference purposes:

These pwm files are based on using Tn5 on genomic DNA from these species -- there really shouldn't be a difference in the sequence bias based on the original species (as is observed for human vs yeast).   For testing this, you would need to peform ATAC-seq / Tn5 tagmentation in genomic DNA for species of interest.  Then `pyatac pwm` script can be used with fasta file for genome and bam file for aligned reads.  Do `pyatac pwm --help` for all options
