### ISSUE TITLE
BAM file for fragment sizes distribution plot

### ISSUE THREAD

**Issue by krouskas** [GreenleafLab/NucleoATAC#49]
Hi Alicia,
I work with ATAC-Seq in human tissues and I would like to use NucleoATAC in order to produce a fragment size distribution (globally and around my peak calls).
I would like to ask you which BAM file you use to produce this plot?
I run PEx100 libraries in IlluminaHiSeq2000.
Do I need to filter BAM files (remove duplicates, keep only properly-paired reads, high MAPQ) before applying NucleoATAC?

Best

**Comment by AliciaSchep** [comment]
I use filtered bam files -- removed duplicates, improper pairs, mapq >30.  The pyatac sizes command should ignore improperly paired reads though, so that filtering isn't critical.
