### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by saschi** [GreenleafLab/NucleoATAC#50]
Hi,

what are the requirements for applying NucleoATAC  to paired-end ATAC data in terms of sequencing depth and read length?

Thanks a lot!

**Comment by AliciaSchep** [comment]
Answering this very late, but in case it is still useful to someone:

We usually do 50 bp paired end.  I don't think longer read depth would really help all that much.

For sequencing depth, for mouse/human samples I would recommend on the order of 100 million reads (after filtering), although depends on data quality (how enriched are reads for open chromatin) & fragment size distribution.  

Many other types of analyses (other than nucleosome positioning) with ATAC-seq  can be done with far fewer reads.
