### ISSUE TITLE
Insertion sites plot around TSS

### ISSUE THREAD

**Issue by krouskas** [GreenleafLab/NucleoATAC#51]
Hi Alicia,

I used NucleoATAC to produce a distribution plot of Tn5 insertion sites around refseq human TSSs. I produced this plot by pyatac_signal (input was the ins.bedgraph from a PE100 BAM file and a bed file with TSS positions).

Does this plot have the expected shape?

Many thanks
Konstantinos
![pyatac_signal_tss_withstrand](https://cloud.githubusercontent.com/assets/22957212/20007856/d0fe1e5e-a2a6-11e6-9254-4f8781ad2c7c.jpg)

**Comment by AliciaSchep** [comment]
Yes that is expected shape.  However we often look at what the height of the peak is relative to the baseline 2 kb away-- we compute the ratio of the top of the peak with that baseline.  For human samples it is generally good for that ratio to be greater than 10, while here it looks like about 3.

**Comment by krouskas** [comment]
Hi Alicia,

Thank you for the answer. Why does exist so much "noise" in this plot? Should I expect a more flattened profile?
I did not smooth at all.

Best
Konstantinos

**Comment by AliciaSchep** [comment]
That looks fairly typical, depending on the sequencing depth.  

One good sign is the more noticeable bump at around 200 bp -- indication of linker region between  +1 and +1 nucleosome
