### ISSUE TITLE
question about occ_track

### ISSUE THREAD

**Issue by duyphamuab** [GreenleafLab/NucleoATAC#54]
Hi, 

I make profiles of sample A and B centered around factor C (+/-300bps) using occ.bedgraph files. What will your interpretation of the results? I think there is nucleosome clearance at the peak center of sample A compared to B. Is it right? 

Thanks, 
Duy

[occ_A.agg.track.pdf](https://github.com/GreenleafLab/NucleoATAC/files/758206/occ_A.agg.track.pdf)
[occ_B.agg.track.pdf](https://github.com/GreenleafLab/NucleoATAC/files/758207/occ_B.agg.track.pdf)

**Comment by AliciaSchep** [comment]
Hi Duy, That would be my interpretation as well, although I would be cautious in that interpretation as the overall magnitude seems low even in A. It would probably be worth looking more into whether 1) results are fairly consistent across all sites with C (by making heatmap for example) and 2) whether signal to noise is adequate to get good occupancy determination

**Comment by duyphamuab** [comment]
Thanks for your help!
