### ISSUE TITLE
Can I run nucleoatac with a consensus peak file?

### ISSUE THREAD

**Issue by ghost** [GreenleafLab/NucleoATAC#56]
Hello,

I have ATAC-seq samples from which I called peaks using MACS2 to create a consensus peak file (as advised by https://academic.oup.com/nar/article-lookup/doi/10.1093/nar/gku351). Now I would like to run nucleoatac to identify nucleosome positions.

nucleoatac run --bed consensus.broadPeaks --bam sample1.bam --fasta mm10.fa --out sample1 --cores 16";

nucleoatac run --bed consensus.broadPeaks --bam sample2.bam --fasta mm10.fa --out sample1 --cores 16";

nucleoatac run --bed consensus.broadPeaks --bam sample3.bam --fasta mm10.fa --out sample1 --cores 16";

... and so on for 32 samples.

Can I pass the same (consensus) peak file to each sample bam file?

Thank you

**Comment by AliciaSchep** [comment]
Yup that should be fine!  

One thing I'll note is that when interpreting the output it is important to remember that lack of nucleosome signal or call on its own does not imply lack of nucleosome; without sufficient reads (i.e. sufficient accessibility at the linkers) NucleoATAC won't be able to detect a nucleosome.  This becomes especially important when considering a set of peaks that is a merge of several peak sets where there may be some peaks with very low coverage in some of the samples.

**Comment by ghost** [comment]
Thank you :)
