### ISSUE TITLE
shifting reads bam for NucleoATAC?

### ISSUE THREAD

**Issue by crazyhottommy** [GreenleafLab/NucleoATAC#58]
Hi,
I was reading, and got to know that one has to shift +4bp and -5bp for the reads on + and - strand for TF footprint https://sites.google.com/site/atacseqpublic/atac-seq-analysis-methods/offsetmethods

I have paired-end reads. If I go with the `bamtobed` and then `awk`, `bedtobam`, I will only get the bam file in a "single end" form. (bedtools bedtobam will not handle pair-end)

should I use bamtobedpe first, then, `awk` then `bedpetobam` ?

what kind of bam files does  `NucleoATAC` expect?

I face the same issue with peak calling by MACS2 after shifting the reads: https://github.com/taoliu/MACS/issues/145 as `-f BAMPE` and `-f BAM` have different behavior.

Thanks!
Tommy

**Comment by AliciaSchep** [comment]
Hi Tommy,

NucleoATAC expects bam files that have not already been shifted!  It does the shifting internally when reading in the bam files.  

For peak calling, shifting of reads isn't likely very important, as it is a pretty minor adjustment and peaks are 100s of basepairs. The shifting is only crucial when doing things where the exact position of the insertion matters at single base resolution.

Cheers,
Alicia

**Comment by crazyhottommy** [comment]
@AliciaSchep Thanks very much for your reply. I understand that shifting is only critical for motif footprinting. does `atactk` `make_cut_matrix` expects the un-shifted bam as well? http://atactk.readthedocs.io/en/latest/usage.html#creating-atac-seq-signal-plots-for-motifs.

Sorry for posting atactk issues here:)

Tommy

**Comment by AliciaSchep** [comment]
Sorry I am not familiar with atactk, don't know the answer to that!
