### ISSUE TITLE
what's the bedtools slop -b size?

### ISSUE THREAD

**Issue by crazyhottommy** [GreenleafLab/NucleoATAC#59]
Hi,

from http://nucleoatac.readthedocs.io/en/latest/nucleoatac/

>3) Sorted bed file with regions for which nucleosome analysis is to be performed. These regions will generally be broad open-chromatin regions (i.e. regions called by MACS2 with the --broad flag). It is potentially advisable to extend these regions a bit (e.g. using bedtools slop). Regions should not overlap so it is advisable to use bedtools merge on these regions.

I called broad peaks with macs2, 
what's the size of  `-b` should be used for `bedtools slop`?
I am using `-b 200bp` 

Thanks,
Tommy

**Comment by AliciaSchep** [comment]
I would recommend between 150 and 250, 200 should be fine.

**Comment by crazyhottommy** [comment]
thanks!
