### ISSUE TITLE
NFR output of nucleoatac

### ISSUE THREAD

**Issue by Flomass** [GreenleafLab/NucleoATAC#60]
Hi,

I have question regarding the nfrpos.bed output of nucleoatac.

In the help it is written "output_basename.nfrpos.bed.gz: NFR positions. Columns are (1) chrom, (2) left boundary (0-based), (3) right boundary (1-based), (4) mean occupancy, (5) minimum upper bound occupancy, (6) insertion density, (7) bias density"

Could you precise what you mean by "mean occupancy" and "insertion density" and "bias density"? Does this count the number of reads with short insert size falling into the nfr region?
I couldn't find this information in the help nor in the genome research paper.

To be a bit more specific:
I have two replicates of ATAC-seq data prepared on cell under the same conditions, and I see a relatively low reproductibility of the NFR regions (~50% of the detected NFRs overlap between the two replicates).
I would like to have a score of the nfr region, notably to see whether the high score regions have a higher reproducibility than the lower score region.
If that's the case I would keep only regions above a given score for instance.
Could I use the  "mean occupancy" of the nfr region, or the "insertion density" for this purpose?

Many thanks in advance, and thanks for this very useful pipeline
Best regards,
Florian

**Comment by AliciaSchep** [comment]
I would not advise using the NFRs regions in that way.  The NFR calling algorithm is very conservative -- it requires two detectable flanking nucleosomes, and so misses some real NFR regions when there was insufficient confidence in calling those adjacent nucleosomes.  For looking at changes in NFR, taking some union set of NFRs and then comparing the quantitative levels of reads mapping to those regions might be a better approach.

**Comment by Flomass** [comment]
Hi Alicia,
Thanks for your answer.
Would you advise to do the same for nucleosomes that are found in one replicates and not in the other?
Thanks
best regards
Florian

**Comment by AliciaSchep** [comment]
Hi Florian,

For the nucleosome positions, NucleoATAC is also generally conservative, and the lack of a nucleosome call should not on its own be taken as indicating a lack of nucleosome (could be insufficient fragments to be able to determine whether there is a nucleosome).  Thus just comparing whether a call was made in one sample or not as a way of trying to say whether a nucleosome is present in one sample or not is generally not a good approach.  Again it could make sense to look at nucleosome calls as candidate positions and then look at rawer data (e.g. fragments and/or nucleosome occupancy or signal tracks) at those positions. 

Cheers,
Alicia

**Comment by Flomass** [comment]
Ok, many thanks for your help,
Cheers,
Florian
