### ISSUE TITLE
Figures 5B, C and D

### ISSUE THREAD

**Issue by naiarabediaga** [GreenleafLab/NucleoATAC#61]
Hi Alicia, 

I have don some ATAC-sequencing on  some activated and inactivated cells, and I would like to compare the nucleosome occupancy of them.  I would like to be able to reproduce the figures 5B, 5C and 5D, of your paper "Structured nucleosome fingerprints enable high-resolution mapping of chromatin architecture within regulatory regions" paper. 

- What files did you use for those figures, i.e. occ.bedgraph  or nucleoatac_signal.bedgraph signal?
- How did you calculate the variable "changes in nucleosome occupancy" from the fig.5C ? 

Thanks a lot

**Comment by AliciaSchep** [comment]
For figures 5B and C +1 and -1 positions were determined using the nucmap_combined file.  For B the shift was taken from those positions.  For C the occupancy at those positions was used (occ.bedgraph) (subtraction of values for the change). 5D also used the occ.bedgraph.

**Comment by naiarabediaga** [comment]
I am sorry for not having answered back Alicia. Your answers helped me create the figures  5B, C and D. Thanks a lot. Naiara

**Comment by PoroProcessor** [comment]
Hi @AliciaSchep, @naiarabediaga, @keyuxi, or anyone else who could help clarify this issue for me further. 

I would like to reproduce Fig. 5B and 5C from [Structured nucleosome fingerprints enable high-resolution mapping of chromatin architecture within regulatory regions](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4617971/) as well; however, I don't quite get what Alicia meant in her previous response. 

1. I could be missing something, but I didn't see any "shift" related information in the nucmap_combined file (using test.nucmap_combined.bed.gz as an example below).
2. When examining the occ.bedgraph (using test.occpeaks.bed.gz as an example below), I am not quite sure what Alicia meant by "subtraction of values for the change"

Thank you for making this tool!

### Example Commands and Data Structure
<details><summary>Details</summary>
<p>

`nucs <- readNucs("test.nucmap_combined.bed.gz")`

`str(nucs)`
> Formal class 'GRanges' [package "GenomicRanges"] with 7 slots
  ..@ seqnames       :Formal class 'Rle' [package "S4Vectors"] with 4 slots
  .. .. ..@ values         : Factor w/ 10 levels "chrII","chrIV",..: 1 2 3 4 5 6 7 8 9 10
  .. .. ..@ lengths        : int [1:10] 8 42 13 37 6 6 7 32 8 10
  .. .. ..@ elementMetadata: NULL
  .. .. ..@ metadata       : list()
  ..@ ranges         :Formal class 'IRanges' [package "IRanges"] with 6 slots
  .. .. ..@ start          : int [1:169] 706773 707048 707186 707349 707544 730126 730375 730573 311790 311950 ...
  .. .. ..@ width          : int [1:169] 1 1 1 1 1 1 1 1 1 1 ...
  .. .. ..@ NAMES          : NULL
  .. .. ..@ elementType    : chr "ANY"
  .. .. ..@ elementMetadata: NULL
  .. .. ..@ metadata       : list()
  ..@ strand         :Formal class 'Rle' [package "S4Vectors"] with 4 slots
  .. .. ..@ values         : Factor w/ 3 levels "+","-","*": 3
  .. .. ..@ lengths        : int 169
  .. .. ..@ elementMetadata: NULL
  .. .. ..@ metadata       : list()
  ..@ seqinfo        :Formal class 'Seqinfo' [package "GenomeInfoDb"] with 4 slots
  .. .. ..@ seqnames   : chr [1:10] "chrII" "chrIV" "chrIX" "chrV" ...
  .. .. ..@ seqlengths : int [1:10] NA NA NA NA NA NA NA NA NA NA
  .. .. ..@ is_circular: logi [1:10] NA NA NA NA NA NA ...
  .. .. ..@ genome     : chr [1:10] NA NA NA NA ...
  ..@ elementMetadata:Formal class 'DFrame' [package "S4Vectors"] with 6 slots
  .. .. ..@ rownames       : NULL
  .. .. ..@ nrows          : int 169
  .. .. ..@ elementType    : chr "ANY"
  .. .. ..@ elementMetadata: NULL
  .. .. ..@ metadata       : list()
  .. .. ..@ listData       :List of 4
  .. .. .. ..$ occ      : num [1:169] 0.828 0.723 0.215 0.313 0.728 ...
  .. .. .. ..$ occ_lower: num [1:169] 0.727 0.571 0.102 0.225 0.604 ...
  .. .. .. ..$ occ_upper: num [1:169] 0.901 0.841 0.35 0.407 0.827 ...
  .. .. .. ..$ type     : chr [1:169] "nuc" "occ" "nuc" "nuc" ...
  ..@ elementType    : chr "ANY"
  ..@ metadata       : list()
  
`nucs_df <- readNucs("test.nucmap_combined.bed.gz", out = "data.frame")`
`head(nucs_df)`
>    chr  start    end       occ occ_lower occ_upper reads type
1 chrII 706773 706774 0.8281394 0.7272269 0.9008745    60  nuc
2 chrII 707048 707049 0.7227476 0.5711453 0.8408011    37  occ
3 chrII 707186 707187 0.2145337 0.1022417 0.3495766    43  nuc
4 chrII 707349 707350 0.3132539 0.2249224 0.4067191    96  nuc
5 chrII 707544 707545 0.7280438 0.6035275 0.8269562    45  nuc
6 chrII 730126 730127 0.7306595 0.6096551 0.8258766    51  nuc

`occ <- readNucs("test.occpeaks.bed.gz")`
`str(occ)`
> Formal class 'GRanges' [package "GenomicRanges"] with 7 slots
  ..@ seqnames       :Formal class 'Rle' [package "S4Vectors"] with 4 slots
  .. .. ..@ values         : Factor w/ 10 levels "chrII","chrIV",..: 1 2 3 4 5 6 7 8 9 10
  .. .. ..@ lengths        : int [1:10] 7 40 11 37 6 5 6 31 8 9
  .. .. ..@ elementMetadata: NULL
  .. .. ..@ metadata       : list()
  ..@ ranges         :Formal class 'IRanges' [package "IRanges"] with 6 slots
  .. .. ..@ start          : int [1:160] 706783 707048 707385 707557 730112 730370 730604 311832 312041 312264 ...
  .. .. ..@ width          : int [1:160] 1 1 1 1 1 1 1 1 1 1 ...
  .. .. ..@ NAMES          : NULL
  .. .. ..@ elementType    : chr "ANY"
  .. .. ..@ elementMetadata: NULL
  .. .. ..@ metadata       : list()
  ..@ strand         :Formal class 'Rle' [package "S4Vectors"] with 4 slots
  .. .. ..@ values         : Factor w/ 3 levels "+","-","*": 3
  .. .. ..@ lengths        : int 160
  .. .. ..@ elementMetadata: NULL
  .. .. ..@ metadata       : list()
  ..@ seqinfo        :Formal class 'Seqinfo' [package "GenomeInfoDb"] with 4 slots
  .. .. ..@ seqnames   : chr [1:10] "chrII" "chrIV" "chrIX" "chrV" ...
  .. .. ..@ seqlengths : int [1:10] NA NA NA NA NA NA NA NA NA NA
  .. .. ..@ is_circular: logi [1:10] NA NA NA NA NA NA ...
  .. .. ..@ genome     : chr [1:10] NA NA NA NA ...
  ..@ elementMetadata:Formal class 'DFrame' [package "S4Vectors"] with 6 slots
  .. .. ..@ rownames       : NULL
  .. .. ..@ nrows          : int 160
  .. .. ..@ elementType    : chr "ANY"
  .. .. ..@ elementMetadata: NULL
  .. .. ..@ metadata       : list()
  .. .. ..@ listData       :List of 3
  .. .. .. ..$ occ      : num [1:160] 0.832 0.723 0.392 0.746 0.753 ...
  .. .. .. ..$ occ_lower: num [1:160] 0.731 0.571 0.289 0.624 0.633 ...
  .. .. .. ..$ occ_upper: num [1:160] 0.904 0.841 0.497 0.841 0.847 ...
  ..@ elementType    : chr "ANY"
  ..@ metadata       : list()

`occ_df <- readNucs("test.occpeaks.bed.gz", out = "data.frame")`
>chr  start    end       occ occ_lower occ_upper reads
1 chrII 706783 706784 0.8317194 0.7308009 0.9036560    58
2 chrII 707048 707049 0.7227476 0.5711453 0.8408011    37
3 chrII 707385 707386 0.3919162 0.2885081 0.4972638    73
4 chrII 707557 707558 0.7462927 0.6239995 0.8409235    47
5 chrII 730112 730113 0.7532233 0.6329301 0.8469757    51
6 chrII 730370 730371 0.7063072 0.6032210 0.7938134    67

</p>
</details>
