### ISSUE TITLE
TypeError: 'int' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by sudarshanchari** [GreenleafLab/NucleoATAC#66]
Hi!
I am trying to run nucleoatac on a few samples and get the following error at step 1 soon after I run the `nucleotac run` command. I have checked the versions, file formats etc and they do not seem to be incorrect. 

But the test file provided seems to run fine and a few of my samples seem to run fine. But most do not and give the same error. So I am slightly unclear how exactly to proceed. Please let me know when you get a chance.

---------Step1: Computing Occupancy and Nucleosomal Insert Distribution---------
Traceback (most recent call last):
  File "path/nucatac_env/bin/nucleoatac", line 33, in <module>
    nucleoatac_main(args)
  File "path/nucatac_env/lib/python2.7/site-packages/nucleoatac/cli.py", line 56, in nucleoatac_main
    run_occ(occ_args)
  File "path/nucatac_env/lib/python2.7/site-packages/nucleoatac/run_occ.py", line 96, in run_occ
    fragment_dist.modelNFR()
  File "path/nucatac_env/lib/python2.7/site-packages/nucleoatac/Occupancy.py", line 58, in modelNFR
    self.nfr_fit0 = FragmentSizes(self.lower,self.upper, vals = gamma_fit(np.arange(self.lower,self.upper),whichres,res_param[whichres]))
  File "path/nucatac_env/lib/python2.7/site-packages/nucleoatac/Occupancy.py", line 36, in gamma_fit
    k = p[0]
TypeError: 'int' object has no attribute '__getitem__'

Thanks and Warm Regards,
SC

**Comment by teryncitino** [comment]
I am currently running into precisely the same issue.
Thanks for posting.
-TC

**Comment by AliciaSchep** [comment]
For one of the samples that did not run correctly, do you have a plot of the fragment size distribution that you could share?

**Comment by sudarshanchari** [comment]
There are 4 samples in this pdf. The first two samples give me that error (think it is obvious why, but just want to be sure) and the remaining two do not.

[pyatac_fragsizes.pdf](https://github.com/GreenleafLab/NucleoATAC/files/1345452/pyatac_fragsizes.pdf)

**Comment by sudarshanchari** [comment]
Even this sample does not work and gives the same error

[pyatac_fragsize_doc2.pdf](https://github.com/GreenleafLab/NucleoATAC/files/1345635/pyatac_fragsize_doc2.pdf)

**Comment by AliciaSchep** [comment]
I think the error is probably related to the spike at very low fragment size; when that spike is higher than the main NFR peak it likely throws off the fitting function (which ultimately led to the confusing and inelegant error message).  

Do you know what precise size that spike is at?  My guess is that the spike reflects an issue with the alignment or read trimming.

**Comment by sudarshanchari** [comment]
I noticed that and was unsure about what exactly it was. That spike seems to be consistently at 19bp (sometimes 19 & 20) with varying heights (but mostly quite high as you can see in those distributions) between samples. 

With respect to the processing, I performed adapter trimming using Trim Galore and used BWA mem to map, with pretty much standard options, then filtered for mitochondria, -q 30 and used only properly mapped + properly paired reads for all further analysis. Do you have any suggestions?

**Comment by sudarshanchari** [comment]
Hi Alicia,
You can close this issue when you get a chance. I have filtered my BAM files for these (random) spikes and nucleoatac does not give any error. These are likely issues with data generation either sample processing or sequencing and not an issue with the analysis pipeline. I double checked by running reads generated from a similar independent experiment through my pipeline.
Thanks a tonne for your help!
sc

**Comment by AliciaSchep** [comment]
In another issue, #10, someone observed short fragments when aligning with BWA mem due to soft-clipping that they didn't get when aligning a different way. Might be relevant to your scenario
