### ISSUE TITLE
biological interpretation of occupancy tracks

### ISSUE THREAD

**Issue by bhatis2** [GreenleafLab/NucleoATAC#69]
Hi Alicia, 
I am having troubles interpreting some of the occupancy data in a biological context. I was hoping you could help me with it. 

![plotprofiles_four_conditions](https://user-images.githubusercontent.com/17554186/31788997-97c1a7c8-b4de-11e7-82d8-be45706b5c34.png)

This is a plotProfile (generated using deeptools) from the nucleosome occupancy (.occ.bedgraph) tracks for four different conditions.
First of all, I was going through your previous answers, and it seems like it's okay to compare occupancy profiles between conditions as the signal is normalized to read depth, provided the signal:noise ratio is comparable, right?

Specific to the experiment:
It's sort of a time course experiment, where condition 1 is the control, and I am looking at two different genomic regions (region 1 and region 2).

Here's my interpretation of the data:
In condition 2 the nucleosome occupancy is re-distributed, and generally occupancy around the +/-1.5kb of the TSS is higher than in condition 1...there seems to be a non-specific re-distribution, leading to loss in resolution of occupancy profiles.
The profiles seems to re-estabilish in conditions 3, and 4 (4 more so than 3).
Also, between the two regions compared, region 1 seems to re-estabilish occupancy profiles sooner, i.e., in condition 3, compared to region 2

I'm not sure if this is reasonable interpretation of the data...any thoughts would be helpful!
Thanks!

**Comment by AliciaSchep** [comment]
hi @bhatis2,

In general terms, the occupancy profile should be okay to compare between conditions provided signal:noise ratio is comparable.  If interested in a particular region or set of regions, I highly recommend looking at "control" regions to see whether changes are specific to region of interest, e.g. if interested in a particular tss, looking at random other tss.  

The occupancy is also not very reliable if there are insufficient reads, so if comparing specific regions I'd also look to see that there isn't a drastic reduction in reads such than in one condition there are barely and reads. Taking a look at the upper and low bound nucleosome occupancy tracks can also be useful for that.

For your specific plots, I think your  interpretation seems reasonable -- that in condition 2 there is not as strong positioning of the +1 and -1 nucleosome.
