### ISSUE TITLE
Narrow/Broad peaks for NucleoATAC

### ISSUE THREAD

**Issue by jma1991** [GreenleafLab/NucleoATAC#72]
I have called narrow/broad/gapped peaks using MACS2 - which of these would you suggest I use for nucleosome positioning with NucleoATAC?

**Comment by AliciaSchep** [comment]
Either the broad or narrow peaks should be fine, just recommend merging overlapping peaks and extending a bit (~100 bp or so) on either side.

**Comment by jma1991** [comment]
Great, thank you very much.
