### ISSUE TITLE
Python3.x support? 

### ISSUE THREAD

**Issue by evanbiederstedt** [GreenleafLab/NucleoATAC#73]
Hi there

It looks like the following doesn't have Python3.x support. 

(1) Could that be more clear in the repo README and in the documentation at http://nucleoatac.readthedocs.io/en/latest/ ?

Perhaps it was there, but I missed it. 

(2) Could we get Python3.x support? 

It looks like the first catch to modify would be the following:

```
except Exception, e:
                    ^
SyntaxError: invalid syntax
```

which is due to comma-separated arguments no longer being the python3.x standard:

http://docs.pythonsprints.com/python3_porting/py-porting.html

One probably needs something like:

    except Exception as e:

**Comment by AliciaSchep** [comment]
re 1, have made more clear in both readme & docs, thanks for suggestion.  

re 2, no plans/timeline for an update for python 3x support -- if anyone has interest & bandwidth, PR welcomed

**Comment by evanbiederstedt** [comment]
> re 2, no plans/timeline for an update for python 3x support -- if anyone has interest & bandwidth, PR welcomed

I've long thought about how this should work in the bioinformatics community.

I'd be happy to help out, if I were to receive some sort of academic kudos. Otherwise, this probably would count as hacks to make software run (which all groups do) or volunteer work.

**Comment by AliciaSchep** [comment]
Yup, lack of incentives for software maintenance & contribution to already published work is definitely a problem in bioinformatics! I'm happy to credit anyone who contributes to NucleoATAC on the README, documentation, etc. Probably can't really help with anything more formal... maybe @wjgreenleaf has ideas?

**Comment by evanbiederstedt** [comment]
> I'm happy to credit anyone who contributes to NucleoATAC on the README, documentation, etc.

I think that's a pretty reasonable solution. Something like

' Individual XYV (institution ABC) contributed to this project/repo by doing this and that'

Then it becomes something people count point to, or put on their CV. 

> Probably can't really help with anything more formal...

There probably are downstream problems with the above approach, but I'm happy to hear what the Greenleaf Lab thinks

**Comment by wjgreenleaf** [comment]
Agree this is a longstanding problem in academic bioinformatics. I will see if anyone in the lab wants to take over the maintenance of this package. It is a bit of a thankless task…

W


William James Greenleaf, PhD
Associate Professor
Genetics Department
Stanford University School of Medicine

Office:  Beckman 257A
Tel:  650 725-3672
Website: http://greenleaf.stanford.edu
Email:  wjg@stanford.edu<mailto:wjg@stanford.edu>

On Jan 28, 2018, at 9:09 PM, Alicia Schep <notifications@github.com<mailto:notifications@github.com>> wrote:


Yup, lack of incentives for software maintenance & contribution to already published work is definitely a problem in bioinformatics! I'm happy to credit anyone who contributes to NucleoATAC on the README, documentation, etc. Probably can't really help with anything more formal... maybe @wjgreenleaf<https://github.com/wjgreenleaf> has ideas?
