### ISSUE TITLE
Seperate Chromosome?

### ISSUE THREAD

**Issue by hmyh1202** [GreenleafLab/NucleoATAC#78]
nucleoatac need a bam file, but one sample could run for 2 days, so can I seperate the bam to each chromosome part to run nucleoatac ?

**Comment by hmyh1202** [comment]
And the upper limit (exclusive) in insert size was always default 251? So why set that value ? Can i be 2000 ?

**Comment by hmyh1202** [comment]
And  the description of the output should be give more detail

**Comment by hmyh1202** [comment]
something wrong with *occpeaks.bed
![default](https://user-images.githubusercontent.com/18067365/36764043-bb676d0e-1c65-11e8-8a94-f1f144a468cb.png)

**Comment by AliciaSchep** [comment]
Sure you can separate out the chromosomes if you want.  If it is taking a long time, running on just one chromosome and then seeing if the results are even useful might be good idea.  Note that if you are not using the cores option, that might be an other way of speeding things up

I would not recommend setting upper insert size to 2000 for the main nucleosome calling scripts -- method is only intended to use mono-nucleosome information, there won't be much if any gain from increasing to 2000 and it will definitely slow things down even more...

**Comment by hmyh1202** [comment]
Thank you so much, @AliciaSchep 
My  read length is PE125, and shift 150bp for the properly alignment reads of BED format, after that peaks was called by MACS2. The final step was to call nucleosome by  using  NucleoATAC. 
And the picture of nuc_dist is below, I am confused about the distribution of frag_size.  

![default](https://user-images.githubusercontent.com/18067365/36821516-483757d0-1d2e-11e8-916e-3b992601ca2a.png)
![default](https://user-images.githubusercontent.com/18067365/36821524-56c29788-1d2e-11e8-9def-a0807a7e0d5b.png)

**Comment by AliciaSchep** [comment]
NucleoATAC does not expect reads to be shifted in any way prior to being used as input.
