### ISSUE TITLE
interpreting occupancy begraph file

### ISSUE THREAD

**Issue by mbaddoo** [GreenleafLab/NucleoATAC#80]
Hello-
I have recently begun using NucleoATAC for analysis of ATACSeq data.  Thanks so much for this tool! I noticed that with all the samples I have processed, the occupancy bedgraph files show sharp drop-offs (sorry that's the best way I can describe it) in coverage (see attached image).  How do I interpret these tracks?  

![occ bedgraph](https://user-images.githubusercontent.com/10704610/42649777-30e1b2f0-85d0-11e8-8a4d-939dd7cbdbe6.png)

Thank you!

**Comment by AliciaSchep** [comment]
Do those correspond to the peaks provided as input?  The occupancy is only computed within the peaks (with a bit extra on each side I think), so there will be sharp cutoffs at the boundaries.

**Comment by mbaddoo** [comment]
Hi Alicia-Thanks so much!  I understand it now.  Appreciate your reply.

**Comment by mbaddoo** [comment]
Hi Alicia-

Thanks so much for your reply!  I understand it now and have closed the issue.

Appreciate your help.

Best-

Melody Cunningham Baddoo
Sr. Research Scientist
Tulane Cancer Center
COBRE Core/Cancer Crusaders Next Generation Sequence Analysis Core
1700 Tulane Avenue, Room 820
New Orleans, LA 70112
504-988-1345
mbaddoo@tulane.edu

________________________________________
