### ISSUE TITLE
Broad vs narrow peaks for NucleoATAC

### ISSUE THREAD

**Issue by mbaddoo** [GreenleafLab/NucleoATAC#81]
Hello-
I read in a previous post that either broad or narrow peaks called from MACS2 can be used as input for NucleoATAC.  Can you explain why, please?  Thanks!

**Comment by AliciaSchep** [comment]
Peaks are used as input to NucleoATAC so as to limit the area of the genome on which the method is applied.  Areas outside of peaks are unlikely to have sufficient read coverage for it to be worth taking the time to run the method on those regions, and the results are unlikely to be useful  (and even if there is some coverage, it may be 'noise' from genome fragmentation unrelated to chromatin signature).   NucleoATAC has no specific requirement for how you find enriched regions of signal along the genome, just strongly recommends that you use some method to pre-filter the regions of the genomes where the method will be applied.

**Comment by mbaddoo** [comment]
Hello Alicia-

Appreciate your reply!  Many thanks!  Yes, I understand why peaks are used as input, my question is if you can give an explanation of why it does not seem to matter if those peaks are broad or narrow, and why in the NucleoATAC method you recommend using broad peaks from MACS2.  I prefer to follow your method prescribed in NucleoATAC but in my analysis of ATACSeq some investigators specifically request that narrowPeaks be used as input.  I can't seem to defend using broad peaks as input save for it is what is used in the NucleoATAC method.  Does that make sense?

Thanks again for all your help.

Best-

Melody

________________________________________

**Comment by AliciaSchep** [comment]
The recommendation is mostly to not use too narrowly-defined peak regions (and the narrow peaks setting will tend to give tighter peak regions).  If a peak arises thanks to a nucleosome depleted region, the strongest concentration of reads will be in that nucleosome free/depleted stretch of DNA, even if the flanking nucleosomes also have some coverage that would enable their identification. If the peak-detection algorithm is geared towards defining narrower signals, it may set the boundaries of the peak to cut off part of those flanking nucleosomes.    With either narrow or broad peaks it is recommended to extend the peaks on both sides a bit, but that recommendation is probably more important for narrow peaks.  If using narrow peaks for other analyses, then it might make sense to use those as input here as well but to extend them on both sides (and merging overlaps that may result).

**Comment by mbaddoo** [comment]
Makes sense! Thanks so much for the explanation.

Sent from my iPhone

On Jul 24, 2018, at 00:25, Alicia Schep <notifications@github.com<mailto:notifications@github.com>> wrote:


The recommendation is mostly to not use too narrowly-defined peak regions (and the narrow peaks setting will tend to give tighter peak regions). If a peak arises thanks to a nucleosome depleted region, the strongest concentration of reads will be in that nucleosome free/depleted stretch of DNA, even if the flanking nucleosomes also have some coverage that would enable their identification. If the peak-detection algorithm is geared towards defining narrower signals, it may set the boundaries of the peak to cut off part of those flanking nucleosomes. With either narrow or broad peaks it is recommended to extend the peaks on both sides a bit, but that recommendation is probably more important for narrow peaks. If using narrow peaks for other analyses, then it might make sense to use those as input here as well but to extend them on both sides (and merging overlaps that may result).
